### ISSUE TITLE
PDF fails resulting in 500 error every time.

### ISSUE THREAD

**Issue by Pashy83** [brunoqs/pdf_export_redmine#5]
Production log states this after 500 failure.  I am attempting to only PDF 2 issues to test if it works.  

Version Redmine 3.3.8 Stable

ActionView::Template::Error (undefined method `full_width_layout?' for #<IssueCustomField:0x007f88bf95b330>):
    1: <%= raw issues_to_pdf(@issues, @project, @query) %>
  plugins/pdf_export_redmine/lib/redmine_issues_pdf_helper_patch.rb:176:in `block (2 levels) in issues_to_pdf_with_full_pdf'
  plugins/pdf_export_redmine/lib/redmine_issues_pdf_helper_patch.rb:176:in `reject'
  plugins/pdf_export_redmine/lib/redmine_issues_pdf_helper_patch.rb:176:in `block in issues_to_pdf_with_full_pdf'
  app/helpers/issues_helper.rb:30:in `block in issue_list'
  app/helpers/issues_helper.rb:26:in `each'
  app/helpers/issues_helper.rb:26:in `issue_list'
  plugins/pdf_export_redmine/lib/redmine_issues_pdf_helper_patch.rb:131:in `issues_to_pdf_with_full_pdf'
  app/views/issues/index.pdf.erb:1:in `_92d1426a9232d2de848174b0fd62fe17'
  plugins/advanced_roadmap/lib/advanced_roadmap/issues_controller_patch.rb:28:in `render'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by brunoqs** [comment]
@Pashy83 Sorry for leaving you waiting, this error occurs because I copied the source code to write to the pdf of the latest version of redmine, so some variables have different names. At the moment I'm not with the redmine environment installed, so I will not be able to resolve the issue now.
Compare this code https://github.com/redmine/redmine/blob/3.3-stable/lib/redmine/export/pdf/issues_pdf_helper.rb with this https://github.com/brunoqs/pdf_export_redmine/blob/master/lib/redmine_issues_pdf_helper_patch.rb.
Hope this helps!

**Comment by jeortizquan** [comment]
Hi here.  I forked a version of this repo and this worked for me in redmine 3.1.1-1 https://github.com/jeortizquan/pdf_export_redmine/tree/feature/redmine-3.1.1-1 if someone needs it.
